import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "@/context";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Spinner from "@/components/Spinner";

//layout
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <GlobalState>
          <main className="flex min-h-screen flex-col">
          <Toaster position="top-right" reverseOrder={false} />
            <Navbar/>
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  );
}
